# Generated by Django 5.1.5 on 2025-02-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikPartner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='languages',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='languages',
            field=models.ManyToManyField(related_name='influencers', to='tikPartner.language'),
        ),
    ]
