# Generated by Django 5.1.5 on 2025-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0003_influencerprofile_stripe_account_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="influencerprofile",
            name="budget_max",
        ),
        migrations.RemoveField(
            model_name="influencerprofile",
            name="budget_min",
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="budget",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
