# Generated by Django 5.1.5 on 2025-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0004_remove_influencerprofile_budget_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="influencerprofile",
            name="average_views",
        ),
        migrations.RemoveField(
            model_name="influencerprofile",
            name="engagement_rate",
        ),
        migrations.RemoveField(
            model_name="influencerprofile",
            name="follower_count",
        ),
        migrations.RemoveField(
            model_name="influencerprofile",
            name="verified_status",
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="display_name",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="video_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
