# Generated by Django 5.1.5 on 2025-04-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0005_remove_influencerprofile_average_views_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="influencerprofile",
            old_name="followers_count",
            new_name="follower_count",
        ),
        migrations.RenameField(
            model_name="influencerprofile",
            old_name="like_count",
            new_name="likes_count",
        ),
        migrations.RemoveField(
            model_name="influencerprofile",
            name="view_count",
        ),
    ]
