# Generated by Django 5.1.5 on 2025-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tikPartner",
            "0006_rename_followers_count_influencerprofile_follower_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="influencerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=6,
                null=True,
            ),
        ),
    ]
