# Generated by Django 5.1.5 on 2025-05-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0007_influencerprofile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="terms",
        ),
        migrations.AddField(
            model_name="contract",
            name="title",
            field=models.CharField(default="ad", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliverable",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliverable",
                to="tikPartner.contract",
            ),
        ),
    ]
