# Generated by Django 5.1.5 on 2025-05-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0008_remove_contract_terms_contract_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverable",
            name="content_file",
        ),
        migrations.RemoveField(
            model_name="deliverable",
            name="content_url",
        ),
        migrations.CreateModel(
            name="DeliverableAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="deliverables/"),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tikPartner.deliverable",
                    ),
                ),
            ],
        ),
    ]
