# Generated by Django 5.1.5 on 2025-05-22 20:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0009_remove_deliverable_content_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverableattachment",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deliverableattachment",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="file"
            ),
        ),
    ]
