# Generated by Django 5.1.5 on 2025-05-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0010_deliverableattachment_original_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="revised_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
