# Generated by Django 5.1.5 on 2025-05-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0011_deliverable_approved_at_deliverable_revised_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="resubmitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
