# Generated by Django 5.1.5 on 2025-05-25 11:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0012_deliverable_resubmitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencerprofile",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="InfluencerPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="portfolio_file"
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to="tikPartner.influencerprofile",
                    ),
                ),
            ],
        ),
    ]
