# Generated by Django 5.1.5 on 2025-05-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0013_influencerprofile_onboarded_influencerportfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencerportfolio",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
