# Generated by Django 5.1.5 on 2025-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0014_influencerportfolio_original_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencerportfolio",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-05-13T13:17:32.895Z"),
            preserve_default=False,
        ),
    ]
