# Generated by Django 5.1.5 on 2025-05-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0015_influencerportfolio_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="tikPartner.contract",
            ),
        ),
    ]
