# Generated by Django 5.1.5 on 2025-05-26 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0016_alter_review_contract"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverable",
            name="feedback",
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
