# Generated by Django 5.1.5 on 2025-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0017_remove_deliverable_feedback_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("submitted", "Submitted"),
                    ("revision", "Revision Required"),
                    ("updated", "Updated"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
