# Generated by Django 5.1.5 on 2025-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0018_alter_deliverable_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="feedback",
            field=models.TextField(blank=True),
        ),
    ]
