# Generated by Django 5.1.5 on 2025-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0020_messagenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="influencerprofile",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="subscription_plan",
            field=models.CharField(
                blank=True,
                choices=[("basic", "Basic"), ("pro", "Pro")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="influencerprofile",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
