# Generated by Django 5.1.5 on 2025-05-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0021_influencerprofile_is_subscribed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandprofile",
            name="verification_documents",
        ),
    ]
