# Generated by Django 5.1.5 on 2025-05-31 11:03

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tikPartner", "0022_remove_brandprofile_verification_documents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispute",
            name="dispute_type",
        ),
        migrations.AlterField(
            model_name="dispute",
            name="contract",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispute",
                to="tikPartner.contract",
            ),
        ),
        migrations.CreateModel(
            name="DisputeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="dispute-file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tikPartner.dispute",
                    ),
                ),
            ],
        ),
    ]
