# Generated by Django 5.1.5 on 2025-05-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tikPartner",
            "0023_remove_dispute_dispute_type_alter_dispute_contract_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispute",
            name="contract",
        ),
    ]
