# Generated by Django 5.1.5 on 2025-05-30 18:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0002_remove_customuser_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile-picture"
            ),
        ),
    ]
